visibility("private")

extra_presets = {
    "incompatible_disallow_empty_glob": struct(
        command = "common",
        default = True,
        description = """\
        Set default value of `allow_empty` to `False` in `glob()`. This prevents a common mistake when
        attempting to use `glob()` to match files in a subdirectory that is opaque to the current package
        because it contains a BUILD file. See https://github.com/bazelbuild/bazel/issues/8195.
        """,
    ),
    # About sandboxing
    # - On Linux, sandboxing is enabled by default for all actions.
    # - A Bazel action can disable sandboxing intentionally by using `tags=["no-sandbox"]`.
    # - Sandboxing can be disabled globally with an option like --spawn_strategy=local.
    #
    # Lets the sandbox create its sandbox directories underneath this path. Specify a path on tmpfs
    # to possibly improve performance a lot when your build / tests have many input files.
    # Note: You need enough RAM and free space on the tmpfs to hold output and intermediate files generated by running actions.
    # build --sandbox_base=/dev/shm
    "incompatible_sandbox_hermetic_tmp": struct(
        command = "build",
        default = True,
        description = """\
        If set to true, each Linux sandbox will have its own dedicated empty directory mounted as /tmp rather than
        sharing /tmp with the host filesystem. Use --sandbox_add_mount_pair=/tmp to keep seeing the host's /tmp in all sandboxes.
        """,
    ),
    "sandbox_fake_hostname": struct(
        command = "build",
        default = True,
        description = """\
        Change the current hostname to 'localhost' for sandboxed actions.
        """,
    ),
    "sandbox_fake_username": struct(
        command = "build",
        default = True,
        description = """\
        Change the current username to 'nobody' for sandboxed actions.
        """,
    ),
    "incompatible_exclusive_test_sandboxed": struct(
        command = "test",
        default = True,
        description = """\
        Allow exclusive tests to run in the sandbox. Fixes a bug where Bazel doesn't enable sandboxing for
        tests with `tags=["exclusive"]`.
        """,
    ),
    # Warn if a test's timeout is significantly longer than the test's actual execution time.
    # Bazel's default for test_timeout is medium (5 min), but most tests should instead be short (1 min).
    # While a test's timeout should be set such that it is not flaky, a test that has a highly
    # over-generous timeout can hide real problems that crop up unexpectedly.
    # For instance, a test that normally executes in a minute or two should not have a timeout of
    # ETERNAL or LONG as these are much, much too generous.
    "test_verbose_timeout_warnings": struct(
        command = "test",
        default = True,
        description = """\
        If true, print additional warnings when the actual test execution time does not match the timeout
        defined by the test (whether implied or explicit).
        """,
    ),
}
