# https://rust-lang.github.io/rust-clippy/master/index.html

disallowed-types = [
    # use the faster & simpler non-poisonable primitives in `parking_lot` instead
    "std::sync::Mutex",
    "std::sync::RwLock",
    "std::sync::Condvar",
    "std::sync::Once",
]

disallowed-methods = [
    "std::env::temp_dir", # use the `tempdir` crate instead
    "std::env::home_dir", # deprecated
]
