[package]
name    = "bits"
edition = "2021"
version = "0.0.0"
publish = false

[dependencies]

[dev-dependencies]
bitvec = { path = "bitvec" }
fenwicktree = { path = "../fenwicktree" }
num = { path = "../num" }
quickcheck = "1"
quickcheck_macros = "1"
