version: "3"

# Use "forwardPorts" in **devcontainer.json** to forward an app port locally.

volumes:
  xdg-cache:
  xdg-config:
  xdg-data:


services:
  workspace:
    build:
      context: ./workspace
    user: "1000:1000"
    command: sleep infinity
    tty: true
    init: true
    volumes:
      - ..:/home/nonroot/trunk
      - xdg-cache:/home/nonroot/.cache
      - xdg-config:/home/nonroot/.config
      - xdg-data:/home/nonroot/.local/share
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
