on:
  workflow_call:

jobs:
  bazel:
    name: Bazel
    runs-on: [ubuntu-22.04]
    env:
      BAZEL: bazel --output_user_root=/tmp/fuzz/
      BAZEL_ARGS: --config=fuzz
      BUILD_TAG_FILTERS: --build_tag_filters=+fuzzing
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        env:
          cache-name: bazel-cache-fuzz
        with:
          path: |
            /tmp/fuzz
            ~/.cache/bazelisk
            ~/Library/Caches/bazelisk
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}-

      # TODO: Test fuzzing targets
      - run: $BAZEL build $BAZEL_ARGS $BUILD_TAG_FILTERS //...
        name: Build
