name: Presubmit

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr:
    name: Check PR
    uses: ./.github/workflows/check-pr.yaml
  testing:
    name: Testing
    needs: check-pr
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    uses: ./.github/workflows/testing.yaml
    with:
      os: ${{ matrix.os }}
