name: Presubmit

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Testing
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    uses: ./.github/workflows/testing.yaml
    with:
      os: ${{ matrix.os }}
  fuzzing:
    name: Fuzzing
    uses: ./.github/workflows/fuzzing.yaml
