on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  bazel:
    name: Bazel
    runs-on: ${{ inputs.os }}
    env:
      BAZEL: bazel --output_user_root=/tmp/ci/
      BAZEL_ARGS: --config=ci

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        env:
          cache-name: bazel-cache
        with:
          # bazelisk stores a bazel binary in the [UserCacheDir](https://pkg.go.dev/os#UserCacheDir).
          path: |
            /tmp/ci
            ~/.cache/bazelisk
            ~/Library/Caches/bazelisk
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}-

      - name: Buildifier
        run: $BAZEL run $BAZEL_ARGS //tool/buildifier

      - name: Build
        run: $BAZEL build $BAZEL_ARGS //...

      - name: Test
        run: $BAZEL test $BAZEL_ARGS //...

      - name: Audit
        if: github.event_name == 'schedule'
        run: $BAZEL run $BAZEL_ARGS //tool/audit
